---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/contacts":
    post:
      summary: Creates a contact
      tags:
      - Contacts
      security:
      - Bearer: {}
      parameters:
      - name: Authorization
        in: header
        schema:
          type: string
      responses:
        '201':
          description: blog created
        '422':
          description: invalid request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                registration_number:
                  type: string
                phone:
                  type: string
                address:
                  type: string
                zip_code:
                  type: string
                latitude:
                  type: integer
                longitude:
                  type: integer
              required:
              - name
              - registration_number
              - address
              - zip_code
              - latitude
              - longitude
  "/blogs/{id}":
    get:
      summary: Retrieves a blog
      tags:
      - Blogs
      - Another Tag
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: blog found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  content:
                    type: string
                required:
                - id
                - title
                - content
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  title:
                    type: string
                  content:
                    type: string
                required:
                - id
                - title
                - content
        '404':
          description: blog not found
        '406':
          description: unsupported accept header
components:
  securitySchemes:
    Bearer:
      type: apiKey
      name: Authorization
      in: header
      description: Your Bearer token
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:3000
