require:
  - rubocop-rails

AllCops:
  NewCops: disable
  TargetRubyVersion: 3.2.2
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'spec/rails_helper.rb'
  SuggestExtensions: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context', 'feature', 'scenario', 'let', 'it']

Metrics/AbcSize:
  Exclude:
  - 'app/controllers/users/*'
  - 'app/controllers/application_controller.rb'

Metrics/MethodLength:
  Exclude:
  - 'app/controllers/application_controller.rb'